### ISSUE TITLE
Running without paid services?

### ISSUE THREAD

**Issue by mustafateke** [sentinel-hub/field_delineation#1]
This is a question rather than an issue. 
I had some difficulty in running the scripts with paid services. 
Would you mind adding a version with previously downloaded data such as L1C/L2A Sentinel-2 imagery? 

Kinds Regards,
Mustafa Teke

**Comment by batic** [comment]
Hi @mustafateke ,

Unfortunately, that would be a lot of data. 

We are planning to update the notebooks, use Batch functionality that is now implemented in sentinelhub-py etc. in the next version (due sometime end November), and we will think about adding the data as well (or reuse some data already available, e.g. from eo-learn LULC example.

Could you please be more specific regarding the difficulties you had?

Best,
Matej

**Comment by LucaScalam** [comment]
Hi,

I'd like to know if there is a chance of running these notebooks with a free trial sentinel-hub account.

If that's the case, I'd need some help on setting a new configuration, because I'm getting the error 

```
{'error': {'status': 403,
  'reason': 'Forbidden',
  'message': 'You are not authorized to perform this action.',
  'code': 'COMMON_INSUFFICIENT_PERMISSIONS'}}
```

whit the code 

```
response = oauth.request("POST", batch_url, headers=headers, json = payload)
response.json()
```

I'm using the same payload and evalscript as you,  just changed the polygon's coordinates.

Best,
Luca

**Comment by batic** [comment]
Hi @LucaScalam,

There are two issues here:
 * Sentinel-Hub BatchAPI is (currently) limited to our enterprise users
 * for BatchAPI you also need to have AWS Account and s3 bucket (properly set up) so that the batch processing jobs can store the output to the bucket

If you'd like to try, we are happy to set-up your (trial) account for BatchAPI as well, but you'll still have to set up the bucket. See https://docs.sentinel-hub.com/api/latest/api/batch/ for more details.

Best of luck,
Matej

**Comment by LucaScalam** [comment]
Understood. 

I'd should try with my own data, I wouldn't need the BatchAPI then.

Is it possible to adapt all the code to use disk storage instead of an S3 bucket ?

**Comment by LucaScalam** [comment]
Thanks for the answer @batic

Understood.

I'd should try with my own data, I wouldn't need the BatchAPI then.

Is it possible to adapt all the code to use disk storage instead of an S3 bucket ?

**Comment by batic** [comment]
If you are not using BatchAPI to retrieve the EO data from SH services (but are either using ProcessingAPI like in [examples](https://eo-learn.readthedocs.io/en/latest/examples/io/SentinelHubIO.html?highlight=SentinelHubInputTask#Example-showcasing-IO-tasks) or your own locally stored data), you have no need for S3 bucket at all.

Best,
Matej

**Comment by LucaScalam** [comment]
I'm happy to hear that.

Thanks Matej, I really appreciate it.

Best,
Luca

**Comment by SandroAlex** [comment]
Hello guys, 

First of all congratulations for the excellent and comprehensive piece of work. After reading your very nice blog post at medium, I became interested in running the 10-notebook workflow in order to better understand all the necessary steps for parcel boundary detection. However, I could not download the data in the first notebook because of an error similar to the one reported in this issue (COMMON_INSUFFICIENT_PERMISSIONS). I do have access to a paid sentinel hub account, even though it is a basic account, not an enterprise one. I also have an AWS bucket permission setting. My question is: could I somehow obtain the same data used in your workflow with these permissions? Sorry for commenting on a closed issue. Thank you very much.

Best regards,
Alex Sandro

**Comment by batic** [comment]
@SandroAlex Please see the response at SH forum.
