### ISSUE TITLE
Input data dimensions and projection: error in predict notebook

### ISSUE THREAD

**Issue by SFrav** [sentinel-hub/field_delineation#10]
Thank you for this great package and tutorial. Really exciting!

We've been trying to run this workflow on our own data but we are having difficulties with the prediction stage. The traceback is below.
Is the error here due to the dimensions of our input data (not square)? Also, we have our data projected to a local crs, should it be in wgs84? Advice on addressing this would be appreciated. We're trying reprojecting and clipping now.

The error seems to occur when building the resUnet model on the pyramidPoolingModule part ([line 427 here](https://github.com/sentinel-hub/eo-flow/blob/d7203fb20bb402857765327244a9448b6105568d/eoflow/models/segmentation_unets.py), and from line [346 here](https://github.com/sentinel-hub/eo-flow/blob/d7203fb20bb402857765327244a9448b6105568d/eoflow/models/layers.py)).  

Traceback (most recent call last):
  File "/home//9predictEOpatches.py", line 81, in <module>
    model = load_model(prediction_config)
  File "/home//fd/prediction.py", line 223, in load_model
    model.build(input_shape)
  File "/home//.local/lib/python3.8/site-packages/eoflow/models/segmentation_unets.py", line 429, in build
    ppm1 = PyramidPoolingModule(filters=32 * self.config.features_root,
  File "/home//.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home//.local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 699, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: Exception encountered when calling layer "pyramid_pooling_module" (type PyramidPoolingModule).

in user code:

File "/home//.local/lib/python3.8/site-packages/eoflow/models/layers.py", line 405, in call  *
        return tf.concat(outputs, axis=-1)

ValueError: Dimension 1 in both shapes must be equal, but are 95 and 81. Shapes are [?,95,48] and [?,81,48]. for '{{node pyramid_pooling_module/concat}} = ConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32](Placeholder, pyramid_pooling_module/sequential/up_sampling2d/resize/ResizeBilinear, pyramid_pooling_module/sequential_1/up_sampling2d_1/resize/ResizeBilinear, pyramid_pooling_module/sequential_2/up_sampling2d_2/resize/ResizeBilinear, pyramid_pooling_module/sequential_3/up_sampling2d_3/resize/ResizeBilinear, pyramid_pooling_module/concat/axis)' with input shapes: [?,79,48,1024], [?,79,48,256], [?,117,48,256], [?,95,48,256], [?,81,48,256], [] and with computed input tensors: input[5] = <-1>.

Call arguments received:
  • inputs=tf.Tensor(shape=(None, 79, 48, 1024), dtype=float32)
  • training=None

**Comment by veseln** [comment]
Hi, 
For prediction, the CRS should not matter. What matters is only the shape of the input. 
I went through our code and realized that some functionality was hardcoded  to our usecase.  

I would suggest removing the padding part https://github.com/sentinel-hub/field-delineation/blob/3e9a493bdfa7146b66abd36a844618250a77e190/fd/prediction.py#L114  and the  cropping part  
https://github.com/sentinel-hub/field-delineation/blob/3e9a493bdfa7146b66abd36a844618250a77e190/fd/prediction.py#L147-L149
 inside of the prediction code. This functionality was there because we were predicting on different-sized inputs than what we trained the model on. This led to some issues with the PyramidPoolingModule that we tried to circumvent with this code (mainly that there was a mismatch between the shape of the input and of the predicted output). If you predict on images that are the same size as what the model was trained on  this is not needed and I suggest removing it.  

If you are predicting on different sized inputs than what the model was trained on, I suggest to proceed with a lot caution, as we noticed some issues with the alignment of the predictions and generally strange behaviour. 

We are planning some updates to the repository which should address this issue and also update/improve some other things,   but this should come later this week / beginning of next week.

**Comment by SFrav** [comment]
Thank you for the detailed post.
I tried commenting out those lines, but unfortunately it throws the same error.

In updates, it would also be useful to have an example evalScript. I wasn't sure how to create a userdata.json file with the right metadata. Also, it seemed odd that the CLP input needed to be a 2 band raster.

**Comment by devisperessutti** [comment]
Hi @SFrav,

Did you change the input size of your arrays or not? I believe the Pyramidal layer, unlike the convolutional layers, only works for square arrays of specific sizes, as mentioned by Nejc above.

Can you try running the prediction with arrays of the same size as in our original notebooks? This should work.

**Comment by SFrav** [comment]
Hi @devisperessutti, I believe the patches are all 256x256 but the prediction ROI isn't square. Thanks, we'll use the clipped version later this week.
